//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class NguoiDung
    {
        public int NguoiDungID { get; set; }

        [DisplayName("Account")]
        [Required(ErrorMessage = "Not Empty")]
        public string TenDangNhap { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Not Empty")]
        public string MatKhau { get; set; }

        [NotMapped]
        [Compare("MatKhau", ErrorMessage = "Mật khẩu không khớp.")]
        [DisplayName("Confirm Password")]
        public string NhapLaiMatKhau { get; set; }

        [DisplayName("Full name")]
        [Required(ErrorMessage = "Not Empty")]
        public string HoTen { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Not Empty")]
        public string Email { get; set; }

        [DisplayName("Role")]
        [Required(ErrorMessage = "Not Empty")]
        public string VaiTro { get; set; }


        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> LanDangNhapCuoi { get; set; }
    }
}
